#!/bin/bash

fd_cmd=(fd --type f --no-ignore "$@")
reload_cmd=$(printf "%q " "${fd_cmd[@]}")

process_cmd='
awk -F"/" '\''{
    if (NF > 1) {
    dir=substr($0, 1, length($0)-length($NF))
    gsub("/", "\x1b[33m/\x1b[34m", dir)
    file=$NF
    printf "\x1b[34m%s\x1b[32m%s\x1b[0m\n", dir, file
    } else {
    printf "\x1b[32m%s\x1b[0m\n", $1
    }
}'\'' | LC_ALL=C sort'

"${fd_cmd[@]}" | eval "$process_cmd" | \
fzf --exact --no-sort --ansi --style full --wrap --delimiter : \
    --preview 'batcat --color=always {}' --preview-window 'hidden' \
    --border top \
    --border-label " $(echo $PWD | sed "s/^[^/]\\+$/\x1b[32m&/" | sed "s/\\(.*\\/\\)\\(.*\\)/\x1b[34m\\1\x1b[32m\\2/" | sed "s/\//\x1b[33m\/\x1b[34m/g") " \
    --color 'fg:252,fg+:252,bg:234,bg+:235,hl:magenta,hl+:magenta,info:144,border:240,prompt:161,pointer:161,marker:118,spinner:118,header:168' \
    --bind "ctrl-r:reload($reload_cmd | $process_cmd)" \
    --bind 'ctrl-l:toggle-preview' \
    --bind "enter:execute-silent(nohup xdg-open {})" \
    --bind "ctrl-o:execute-silent(tmux new-window -n nvim  nvim \"$(realpath \"{}\"\"); tmux select-pane -T editor)" \
    --bind "ctrl-e:execute-silent(~/.SearchFunctions/sub-functions/open_in_file_manager {})" \
    --bind "ctrl-c:execute-silent(echo -n {} | wl-copy)" \
    --bind "ctrl-t:execute-silent(tmux new-window -n infile ~/.SearchFunctions/sub-functions/search_in_single_file \"$(realpath \"{}\"\"); tmux select-pane -T file-content)" \
    --bind "ctrl-u:execute-silent(tmux new-window -n diff ~/.SearchFunctions/sub-functions/show_diffs \"$(realpath \"{}\"\"); tmux select-pane -T git)" \
    --bind "alt-u:execute-silent(tmux new-window -n logs ~/.SearchFunctions/sub-functions/show_logs \"$(realpath \"{}\"\"); tmux select-pane -T git)" \
    --bind "alt-j:execute-silent(tmux new-window -n folders ~/.SearchFunctions/sub-functions/folder_list_ugrep; tmux select-pane -T folder-list)" \
    --bind "ctrl-j:execute-silent(tmux new-window -n files ~/.SearchFunctions/sub-functions/file_list; tmux select-pane -T file-list)" \
    --bind 'home:last,end:first' \
    --bind 'alt-up:preview-page-up' \
    --bind 'alt-down:preview-page-down' \
    --preview-window='up:50%:wrap'
