#!/bin/zsh

FILE="$1"
QUERY="$2"

[[ -z "$FILE" ]] && { echo "Please provide a file name"; exit 1; }

export GREP_COLORS="ms=01;31:mc=01;31:sl=:cx=35:fn=35:ln=32:bn=32:se=36"

FZF_DEFAULT_COMMAND="ugrep -Un --color=always --smart-case \"$QUERY\" '$FILE' | tr -d '\r'" \
fzf --ansi \
    --no-sort \
    --exact \
    --style full \
    --wrap \
    --border rounded \
    --query "$QUERY" \
    --border-label " $(echo "$FILE" | sed "s/^[^/]\\+$/\x1b[32m&/" | sed "s/\\(.*\\/\\)\\(.*\\)/\x1b[34m\\1\x1b[32m\\2/" | sed "s/\//\x1b[33m\/\x1b[34m/g") " \
    --delimiter : \
    --preview '
        LINE={1}
        ugrep -Un "" '"'$FILE'"' | tr -d "\r" | awk -v line=$LINE '"'"'
            BEGIN {FS=":"}
            $1 == line {printf "\033[32m%4d\033[0m:\033[33m%s\033[0m\n", $1, substr($0,length($1)+2); next}
            {printf "\033[32m%4d\033[0m:%s\n", $1, substr($0,length($1)+2)}
        '"'" \
    --color 'preview-fg:bright-magenta,fg:green,fg+:green,bg:234,bg+:235,hl:red,hl+:red,info:144,border:240,prompt:161,pointer:161,marker:118,spinner:118,header:168' \
    --layout reverse \
    --preview-window "down:75%:wrap:+{1}-5" \
    --bind "alt-up:preview-page-up" \
    --bind "alt-down:preview-page-down" \
    --bind 'home:first,end:last' \
    --bind "ctrl-l:toggle-preview" \
    --bind "enter:execute-silent(nohup xdg-open \"$FILE\" >/dev/null 2>&1 &)" \
    --bind "ctrl-c:execute-silent(echo -n \"$FILE\" | wl-copy)" \
    --bind "ctrl-o:execute-silent(tmux new-window -n \"$FILE\" \"nvim '$FILE'\")" \
    --bind "ctrl-e:execute-silent(nohup dolphin --select \"$FILE\" >/dev/null 2>&1 &)" \
    --bind "ctrl-t:execute-silent(tmux new-window -n search '~/.SearchFunctions/sub-functions/search_in_single_file \"$FILE\"')" \
    --bind "ctrl-u:execute-silent(tmux popup -E -w 95% -h 95% 'cd \"$PWD\" && zsh -ic \"show-logs \\\"$FILE\\\"\"')" \
    --bind "ctrl-p:execute-silent(tmux popup -E -w 95% -h 95% 'cd \"$PWD\" && ~/.SearchFunctions/sub-functions/search_in_single_file \"$FILE\"')" \
    --bind "ctrl-i:execute-silent(tmux popup -E -w 95% -h 95% 'cd \"$PWD\" && ~/.SearchFunctions/sub-functions/file_list')" \
    --bind "change:reload(
        query={q}
        if [ -n \"\$query\" ]; then
            pattern=\"\$(echo \"\$query\" | tr ' ' '|')\"
            ugrep -Un --color=always --smart-case \"\$pattern\" \"$FILE\" | tr -d '\r' || true
        else
            ugrep -Un --color=always --smart-case '' \"$FILE\" | tr -d '\r' || true
        fi
    )" \
    --bind "ctrl-r:reload(
        query={q}
        if [ -n \"\$query\" ]; then
            pattern=\"\$(echo \"\$query\" | tr ' ' '|')\"
            ugrep -Un --color=always --smart-case \"\$pattern\" \"$FILE\" | tr -d '\r' || true
        else
            ugrep -Un --color=always --smart-case '' \"$FILE\" | tr -d '\r' || true
        fi
    )"
